export type AvailableIcons =
  | 'add'
  | 'arrowDown'
  | 'bell'
  | 'bellBall'
  | 'close'
  | 'dashboard'
  | 'filter'
  | 'key'
  | 'lineArrowDown'
  | 'lineArrowUp'
  | 'logo'
  | 'logoSmall'
  | 'mail'
  | 'person'
  | 'questionMarkRounded'
  | 'search'
  | 'transaction';
