name: deploy pipeline
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test:ci

      - name: Check circular dependencies
        run: npm run circular

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vercel CLI
        uses: actions/checkout@v2

      - name: Pull Vercel Environment Information
        run: npm install --global vercel@latest


      - name: Build Project Artifacts
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy app
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}